import type { Metadata } from "next";
import "./globals.css";
import {GlobalContextProvider} from './contexts/stateContext';
import {AuthContextProvider} from './contexts/AuthContext';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider>
            {children}
        </GlobalContextProvider></body>
    </html>
  );
}
